### ISSUE TITLE
README feels off atm

### ISSUE THREAD

**Issue by tyvdh** [cloudflare/durable-objects-webpack-commonjs#10]
I'm still trying to wrap my head around exactly what's going on but I don't think everything is _quite_ right between what I'm seeing in practice and what the README is telling me I should be seeing.

> Webpack is configured to output a bundled ES Module to dist/index.mjs.

I do not see this file after running `npm run build`
![Screen Shot 2021-06-02 at 11 08 54 AM](https://user-images.githubusercontent.com/4383610/120505396-ef28c480-c392-11eb-9fb8-c53ec91c62f0.png)

It would be nice if the README could be revisited and maybe this entire repo given a toothcomb once over to ensure it's all up-to-date with recent changes in wrangler and the durable object features.

Thanks!

**Comment by tyvdh** [comment]
> On your first publish, you must use wrangler publish --new-class to allow the Counter class to implement Durable Objects.

```
% wrangler publish --new-class
error: The argument '--new-class <new-class>...' requires a value but none was supplied

USAGE:
    wrangler publish --config <config> --new-class <new-class>...

For more information try --help
```

I'm guessing it's ` wrangler publish --new-class Counter`?

**Comment by koeninger** [comment]
opened https://github.com/cloudflare/durable-objects-webpack-commonjs/pull/11  let me know if anything else needs clarifying

**Comment by tyvdh** [comment]
Nice! Another weird thing I've noticed and this may have more to do with using webpack@5 is that I seem unable to use built in modules until they are explicitly added. 

e.g. 
```
// index.js
...
return new Response(Buffer.from('Hello World').toString('base64'))
```
Returns
`// Buffer is not defined`

Expected
`// SGVsbG8gV29ybGQ=`

Can be fixed via 
```
// webpack.config.js
module.exports = {
  ...
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    })
  ]
}
```

It begs the question though is this the required method and if so what all should be added to that object to cover all possible scenarios?

**Comment by koeninger** [comment]
Buffer is a Node.js api, not a web standard browser api, right?  Workers in general doesn't have Node.js apis built in.

**Comment by tyvdh** [comment]
Hmm good point, it's an incredibly common package but yeah a discussion for another time and not in this repo. Changes look good. Closing the ticket.
